### INPUT ###

input {
    kb_layout = us

    repeat_rate = 35
    repeat_delay = 350

    sensitivity = 0
    accel_profile = flat
    scroll_button = 0
    scroll_factor = 1.0

    follow_mouse = 1
    follow_mouse_threshold = 0.0

    focus_on_close = 1
    mouse_refocus = true
    force_no_accel = false
    float_switch_override_focus = 1

    scroll_button_lock = false
    numlock_by_default = false

    special_fallthrough = false
}

binds {
    pass_mouse_when_bound = false
    scroll_event_delay = 150

    workspace_back_and_forth = false
    hide_special_on_workspace_change = true
    allow_workspace_cycles = false
    workspace_center_on = 0

    movefocus_cycles_fullscreen = true

    disable_keybind_grabbing = false
    drag_threshold = 0
}

cursor {
    enable_hyprcursor = true
    
    invisible = false
    hide_on_key_press = false

    hotspot_padding = 0
    inactive_timeout = 0
    
    no_warps = false
    persistent_warps = false
    warp_on_change_workspace = 0
    warp_on_toggle_special = 0
    warp_back_after_non_mouse_input = false

    zoom_factor = 1
    zoom_rigid = false
    zoom_detached_camera = true

    use_cpu_buffer = 2
}