##################
##### LAYOUT #####
##################

dwindle {
    pseudotile = true

    force_split = 0
    preserve_split = true
    smart_split = false
    smart_resizing = true

    default_split_ratio = 1
}

master {
    new_status = master
}