#########################
##### MISCELLANEOUS #####
#########################

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_scale_notification = true
    background_color = 0xD3D3D3

    font_family = 'Jetbrains Mono'

    vfr = true
    vrr = 0

    mouse_move_enables_dpms = true
    key_press_enables_dpms = true

    allow_session_lock_restore = true
    session_lock_xray = true

    always_follow_on_dnd = true
    layers_hog_keyboard_focus = true
    focus_on_activate = false
    on_focus_under_fullscreen = 2
    exit_window_retains_fullscreen = false
    initial_workspace_tracking = 1

    animate_manual_resizes = false
    animate_mouse_windowdragging = false

    enable_swallow = false
    swallow_regex = []
    swallow_exception_regex = []

    middle_click_paste = false
    disable_autoreload = false
    size_limits_tiled = false

    enable_anr_dialog = true
    anr_missed_pings = 5

}

xwayland {
    enabled = true
    use_nearest_neighbor = true
    force_zero_scaling = true
}

opengl {
    nvidia_anti_flicker = true
}

ecosystem {
    no_update_news = false
    no_donation_nag = true
    enforce_permissions = false
}

quirks {
    prefer_hdr = 0
}