### BEHAVIORS ###

monitor = , 2560x1440@240, 0x0, 1.25

xwayland {
    force_zero_scaling = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    font_family = 'Jetbrains Mono'

    animate_manual_resizes = true
    animate_mouse_windowdragging = false

    middle_click_paste = false
}