#############
### RULES ###
#############

##### Floating Apps #####

# Center all floating windows
windowrule = center true, match:float true, match:xwayland false

windowrule {
    name = dolphin

    match:class = org.kde.dolphin

    float = true
    move = (cursor_x-window_w*0.5) (cursor_y-window_h*0.5)
}

windowrule {
    name = bluetooth-manager

    match:class = blueman-manager

    float = true
    center = true
    persistent_size = false
}

windowrule {
    name = wev

    match:class = wev

    float = true
    center = true
    size = 300 300
}

windowrule {
    name = hyprpolkitagent

    match:class = hyprpolkitagent

    float = true
    center = true
}

##### Steam #####

windowrule {
    name = steam-settings

    match:class = steam
    match:title = Steam Settings

    float = true
    center = true
    min_size = 10 10
}

windowrule {
    name = steam-friends-list

    match:class = steam
    match:title = Friends List

    float = true
    center = true
    min_size = 10 10
}

windowrule {
    name = steam-games

    match:class = (steam_app_(default|[0-9]+))|gamescope

    immediate = true
    idle_inhibit = always
    pseudo = true
}

windowrule {
    name = wallpaperengine

    match:class = (steam_app_(default|[0-9]+))|gamescope
    match:title = Wallpaper UI

    float = true
}

##### Other Games #####

windowrule {
    name = roblox

    match:class = org.vinegarhq.Sober

    float = true
    center = true
    size = 1280 720
    immediate = true
    idle_inhibit = always
}

windowrule {
    name = minecraft

    match:class = ^Minecraft.*

    float = true
    center = true
    size = 1280 720
    immediate = true
    idle_inhibit = always

}

##### Smart Gaps/Workspaces #####

# Special workspace : system
windowrule = border_size 0, match:float 0, match:workspace n[e:system]
windowrule = opacity 0.85, rounding 6, match:workspace n[e:system]

# Single window workspaces
workspace = w[tv1], gapsout:5, gapsin:5
windowrule = border_size 0, rounding 6, match:float 0, match:workspace w[tv1]

# Fullscreen window
workspace = f[1], gapsout:5, gapsin:5, bordersize:0
windowrule = rounding 6, match:workspace f[1]

##### Miscellaneous #####
windowrule {
    name = suppress-maximize-events

    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags

    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = true
}