###################
##### STARTUP #####
###################

##### Initialize #####

    # Session
    exec-once = $browser
    exec-once = discord

    exec-once = [workspace special:system silent; group set always] $terminal -e sh -c "fastfetch; exec $SHELL"
    exec-once = [workspace special:system silent] $terminal -e sh -c "htop; exec $SHELL"
    
    # User
    exec-once = linux-wallpaperengine --scaling fill --volume 0 --screen-root DP-2 $wallpaper_id
    exec-once = clipse -listen

    # System
    exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # kbuildsycoca6
    exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
    exec-once = xwaylandvideobridge
    exec-once = swaync
    exec-once = hypridle

    # Extra
    exec-once = trash-empty 30
