###################
##### STARTUP #####
###################

##### Initialize #####
    exec-once = $browser
    exec-once = discord
    # exec-once = spotify-launcher

    exec-once = [workspace special:system silent] $terminal -e sh -c "fastfetch; exec $SHELL"
    exec-once = [workspace special:system silent; float; size 1100 500; move monitor_w-1100-15 15; float 0] $terminal -e sh -c "htop; exec $SHELL"

    exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # kbuildsycoca6
    exec-once = swaync
    exec-once = linux-wallpaperengine --scaling fill --volume 0 --screen-root DP-2 $wallpaper_id
    exec-once = clipse -listen

    exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
    exec-once = xwaylandvideobridge
    exec-once = trash-empty 30
