### STARTUP ###

# Initialize
    exec-once = $browser
    exec-once = $terminal -e sh -c "fastfetch; exec $SHELL"
    exec-once = discord

    exec-once = swaync
    #exec-once = waybar
    exec-once = linux-wallpaperengine --scaling fill --silent --screen-root DP-2 $wallpaper_id

    exec-once = systemctl --user start hyprpolkitagent
