#########################
##### hyprland.conf #####
#########################

##### Paths #####
$hypr = ~/Dotfiles/hypr
$hyprland = $hypr/hyprland

##### Display #####
    monitor = , 2560x1440@240, 0x0, 1.25

##### Configs #####
    source = $hypr/variables.conf
    
    source = $hyprland/misc.conf
    source = $hyprland/input.conf
    source = $hyprland/env.conf
    source = $hyprland/layout.conf
    source = $hyprland/group.conf
    source = $hyprland/startup.conf
    source = $hyprland/rules.conf
    source = $hyprland/keybinds.conf
    source = $hyprland/animation.conf
    source = $hyprland/general.conf
    source = $hyprland/decoration.conf

