#####################
##### VARIABLES #####
#####################

##### Binds #####

    $main_mod = SUPER

##### Apps #####

    $terminal = alacritty
    $file_manager = dolphin
    $app_menu = rofi
    $browser = firefox

##### Customization #####

    # Settings
    $wallpaper_id = 2234208649
    $font_family = 'Jetbrains Mono Nerd Font'
    $bool_vfr = true
    $value_vrr = 0
    $bool_allow_tearing = true
    $layout = dwindle
    $int_repeat_rate = 35
    $int_repeat_delay = 350

    # Rounding
    $int_rounding = 10
    $float_rounding_power = 2.5

    # Borders
    $int_border_size = 2
    $int_gaps_in = 5
    $int_gaps_out = 15
    $int_float_gaps = 15
    $col_active_border = rgb(3083ff) rgb(c4c4c4) rgb(c4c4c4) rgb(3083ff) 45deg
    $col_inactive_border = rgb(336dc4) rgb(b0b0b0) rgb(b0b0b0) rgb(336dc4) 45deg
    
    # Opacity
    $float_active_opacity = 1.0
    $float_inactive_opacity = 1.0
    $float_fullscreen_opacity = 1.0

    # Blur
    $bool_blur_enabled = true
    $int_blur_size = 4
    $int_blur_passes = 2
    $float_blur_noise = 0.02
    $float_blur_contrast = 1.2
    $float_blur_brightness = 1.0
    $float_blur_vibrancy = 0.2
    $float_blur_vibrancy_darkness = 0.4
    $bool_xray = false
    $bool_popups = true

    # Shadows
    $bool_shadows_enabled = true
    $int_shadow_range = 10
    $int_render_power = 3
    $col_shadow_active = rgba(000000aa)
    $col_shadow_inactive = rgba(00000088)

    # Dim
    $bool_dim_modal = false
    $bool_dim_inactive = false
    $float_dim_strength = 0.2
    $float_dim_special = 0.4
    $float_dim_around = 0.4

    # Snap
    $bool_snap_enabled = true
    $bool_snap_window_gap = 5
    $bool_snap_monitor_gap = 10

    # Animations
    $bool_anim_enabled = true