### DECORATIONS ###

decoration {
    rounding = $rounding
    rounding_power = $rounding_power

    active_opacity = $win_active_opacity
    inactive_opacity = $win_inactive_opacity
    fullscreen_opacity = $win_fullscreen_opacity

    dim_inactive = false
    dim_strength = 0.2
    dim_modal = false

    border_part_of_window = true

    blur {
        enabled = $blur_enabled

        size = $blur_size
        passes = $blur_passes

        noise = 0.02
        contrast = 1.2
        brightness = 1.0
        vibrancy = 0.2
        vibrancy_darkness = 0.4

        ignore_opacity = true
        new_optimizations = true
        xray = false
        popups = true
    }

    shadow {
        enabled = $shadows_enabled
        range = $shadow_range
        render_power = 3
        scale = 1.0

        color = $shadow_active_color
        color_inactive = $shadow_inactive_color
        
        ignore_window = true
        sharp = false
    }
}