### GENERAL ###

general {
    gaps_in = 5
    gaps_out = 15
    float_gaps = 15
    #gaps_workspaces = 10

    border_size = 2
    col.active_border = $active_border_color
    col.inactive_border = $inactive_border_color

    resize_on_border = false
    extend_border_grab_area = false
    hover_icon_on_border = true

    allow_tearing = true

    layout = $layout
    
    snap {
        enabled = true

        window_gap = 10
        monitor_gap = 15

        border_overlap = true
        respect_gaps = true
    }
}
