### GENERAL ###

general {
    border_size = 2
    gaps_in = 5
    gaps_out = 15
    float_gaps = 15
    gaps_workspaces = 0

    col.active_border = $active_border_color
    col.inactive_border = $inactive_border_color

    layout = $layout

    allow_tearing = true
    no_focus_fallback = false

    resize_on_border = false
    extend_border_grab_area = false
    hover_icon_on_border = false
    
    snap {
        enabled = true

        window_gap = 10
        monitor_gap = 15

        border_overlap = false
        respect_gaps = true
    }
}
