#########################
##### hypridle.conf #####
#########################

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock screen
listener {
    timeout = 900 # 15min
    on-timeout = loginctl lock-session
}

# Turn off screen
listener {
    timeout = 1200 # 20min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Dim screen
listener {
    # todo
}

# Sleep
listener {
    # todo
}