#########################
##### hyprlock.conf #####
#########################

##### GENERAL #####

general {
    hide_cursor = false
    ignore_empty_input = true
    text_trim = true

    immediate_render = false
    fractional_scaling = true
    screencopy_mode = 0

    fail_timeout = 1500
}

auth {
    # defaults
}

animations {
    enabled = true
    # todo
}

background {
    monitor =
    path = ~/.currentprofile/wallpaper

    blur_size = 4
    blur_passes = 2

    contrast = 1
    brightness = 0.75
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

##### INPUT FIELD #####

input-field {
    monitor =

    size = 300, 50
    rounding = 16
    outline_thickness = 2
    shadow_passes = 1
    shadow_size = 6

    inner_color = rgba(0, 0, 0, 0.41)
    outer_color = rgba(255, 255, 255, 0)

    check_color = rgba(178, 178, 178, 0.28)
    fail_color = rgba(227, 227, 227, 0.65)k

    font_color = rgba(108, 108, 108, 0.41)
    capslock_color = rgba(125, 125, 125, 0.57)

    fade_on_empty = false
    hide_input = false
    swap_font_color = false

    font_family = Cascadia Code Regular
    placeholder_text = <i><span foreground="##ffffff26">password</span></i>
    check_text = #<i><span foreground="##ffffff69">?</span></i>
    fail_text = <i><span foreground="##ffffff26">try again</span></i>
    dots_text_format = *
    dots_size = 0.3
    dots_spacing = 0.4
    dots_center = true
    dots_rounding = -1

    position = 0, -150
    halign = center
    valign = center
    zindex = 0
}

##### TIME AND DATE #####

label {
    monitor =

    text = cmd[update:1000] echo "$(date +"%-I:%M")"
    text_align = center

    color = rgba(255, 255, 255, 0.61)

    font_size = 135
    font_family = Cascadia Code Semibold

    rotate = 0
    position = 0, 360
    halign = center
    valign = center
    zindex = 1
}

label {
    monitor =

    text = cmd[update:1000] echo "$(date +"%A, %B %-d")"
    text_align = center

    color = rgba(255, 255, 255, 0.68)

    font_size = 25
    font_family = Cascadia Code Semibold

    rotate = 0
    position = 0, 250
    halign = center
    valign = center
    zindex = 1
}

##### PROFILE PICTURE #####

image {
    monitor =
    path = ~/.currentprofile/face

    size = 120
    rounding = -1
    border_size = 3
    border_color = rgba(0, 0, 0, 0.55)
    shadow_color = rgba(39, 39, 39, 0.16)
    shadow_passes = 2
    shadow_size = 2

    rotate = 0
    position = 0,15
    halign = center
    valign = center
    zindex = 0
}

##### GREETING #####

label {
    monitor =

    text = $USER
    text_align = center

    color = rgba(164, 164, 164, 0.66)

    font_size = 14
    font_family = Cascadia Code Regular

    rotate = 0
    position = 0, -80
    halign = center
    valign = center
    zindex = 1
}

##### BACKGROUNDS #####

# Greeting
shape {
    monitor =
    color = rgba(0, 0, 0, 0.59)

    rounding = 10
    border_size = 0
    border_color = rgba(0, 207, 230, 1)

    size = 100, 40
    rotate = 0
    position = 0, -80
    halign = center
    valign = center
    zindex = 0
}

# Greeting, profile picture, input field
shape {
    monitor =
    color = rgba(0, 0, 0, 0.36)

    rounding = 25
    border_size = 0
    border_color = rgba(0, 207, 230, 1)

    size = 400, 340
    rotate = 0
    position = 0, -50
    halign = center
    valign = center
    zindex = 0
}

# Time and date
# shape {
#     monitor =
#     color = rgba(0, 0, 0, 0.36)

#     rounding = 25
#     border_size = 0
#     border_color = rgba(0, 207, 230, 1)

#     size = 650, 320
#     rotate = 0
#     position = 0, 335
#     halign = center
#     valign = center
#     zindex = 0
# }