### hyprland.conf CONSTRUCTOR ###

$conf_files = ~/Dotfiles/hyprland
$user = $conf_files/user
$themes = $conf_files/themes
$system = $conf_files/system
$vars = $conf_files/vars

monitor = , 2560x1440@240, 0x0, 1.25

# Vars
    source = $vars/globals.conf

# System
    source = $system/misc.conf
    source = $system/input.conf
    source = $system/rules.conf
    source = $system/layout.conf

# User
    source = $user/startup.conf
    source = $user/env.conf
    source = $user/keybinds.conf

# Themes
    source = $themes/animation.conf
    source = $themes/cursor.conf
    source = $themes/general.conf
    source = $themes/decoration.conf

