#########################
##### hyprland.conf #####
#########################

$conf_files = ~/Dotfiles/hyprland
$user = $conf_files/user
$themes = $conf_files/themes
$system = $conf_files/system
$vars = $conf_files/vars

##### Vars #####
    source = $vars/globals.conf

##### Display #####
    monitor = , 2560x1440@240, 0x0, 1.25

##### System #####
    source = $system/misc.conf
    source = $system/input.conf
    source = $system/env.conf
    source = $system/layout.conf

##### User #####
    source = $user/startup.conf
    source = $user/rules.conf
    source = $user/keybinds.conf

##### Themes #####
    source = $themes/animation.conf
    source = $themes/general.conf
    source = $themes/decoration.conf

