### hyprland.conf CONSTRUCTOR ###

$conf_files = ~/dotfiles/hyprland
$functions = $conf_files/functions
$themes = $conf_files/themes
$controls = $conf_files/controls
$vars = $conf_files/vars

# Vars
    source = $vars/globals.conf

# Controls
    source = $controls/behavior.conf
    source = $controls/input.conf
    source = $controls/windowrules.conf
    source = $controls/layout.conf

# Functions
    source = $functions/startup.conf
    source = $functions/env.conf
    source = $functions/keybinds.conf

# Themes
    source = $themes/animation.conf
    source = $themes/cursor.conf
    source = $themes/decoration.conf

