#######################
##### DECORATIONS #####
#######################

decoration {
    rounding = $int_rounding
    rounding_power = $float_rounding_power

    active_opacity = $float_active_opacity
    inactive_opacity = $float_inactive_opacity
    fullscreen_opacity = $float_fullscreen_opacity

    dim_modal = $bool_dim_modal
    dim_inactive = $bool_dim_inactive
    dim_strength = $float_dim_strength
    dim_special = $float_dim_special
    dim_around = $float_dim_around

    border_part_of_window = true

    blur {
        enabled = $bool_blur_enabled

        size = $int_blur_size
        passes = $int_blur_passes

        noise = $float_blur_noise
        contrast = $float_blur_contrast
        brightness = $float_blur_brightness
        vibrancy = $float_blur_vibrancy
        vibrancy_darkness = $float_blur_vibrancy_darkness

        ignore_opacity = true
        new_optimizations = true
        xray = $bool_xray
        popups = $bool_popups
        input_methods = false
        special = false
    }

    shadow {
        enabled = $bool_shadows_enabled
        range = $int_shadow_range
        render_power = $int_render_power
        offset = 0, 0
        scale = 1.0

        color = $col_shadow_active
        color_inactive = $col_shadow_inactive
        
        ignore_window = true
        sharp = false
    }
    
}