###################
##### GENERAL #####
###################

general {
    border_size = $int_border_size
    gaps_in = $int_gaps_in
    gaps_out = $int_gaps_out
    float_gaps = $int_float_gaps
    gaps_workspaces = 0

    col.active_border = $col_active_border
    col.inactive_border = $col_inactive_border

    layout = $layout

    allow_tearing = $bool_allow_tearing
    no_focus_fallback = false

    resize_on_border = false
    extend_border_grab_area = false
    hover_icon_on_border = false
    
    snap {
        enabled = $bool_snap_enabled

        window_gap = $bool_snap_window_gap
        monitor_gap = $bool_snap_monitor_gap

        border_overlap = false
        respect_gaps = true
    }
}
