##################
##### GROUPS #####
##################

group {
    auto_group = true
    insert_after_current = true
    focus_removed_window = true

    drag_into_group = 2
    merge_groups_on_drag = true
    merge_groups_on_groupbar = true
    merge_floated_into_tiled_on_groupbar = false
    group_on_movetoworkspace = false

    col.border_active = $col_active_border
    col.border_inactive = $col_inactive_border
    col.border_locked_active = $col_active_border
    col.border_locked_inactive = $col_inactive_border

    groupbar {
        enabled = true

        font_family = JetBrains Mono
        font_size = 15
        font_weight_active = semibold
        font_weight_inactive = normal

        blur = true
        gradients = true
        gradient_rounding = 6
        gradient_rounding_power = 2.5
        rounding = 8
        rounding_power = 2
        round_only_edges = false
        gradient_round_only_edges = false
        
        height = 30
        indicator_gap = 0
        indicator_height = 0

        gaps_in = 3
        gaps_out = 3
        keep_upper_gap = false

        text_color = rgba(255, 255, 255, 0.98)
        col.active = rgba(0,0,0,0.61)
        col.inactive = rgba(0,0,0,0.46)
        col.locked_active = rgba(0,0,0,0.71)
        col.locked_inactive = rgba(0,0,0,0.56)
    }
}