#############
### RULES ###
#############

# --- Default rules: OBS Studio, Bitwarden, Obsidian --- #

##### Floating Apps #####

# Center all floating windows
windowrule = center true, match:float true, match:xwayland false

windowrule {
    name = mid-sized-apps

    match:class = ^(gimp|org\.openrgb\.OpenRGB|qt6ct|nwg-look|kvantum.*)$
    match:title = negative:^(GIMP Startup)$|^(Open Kvantum).*|^(Pick).*

    float = true
    center = true
    size = 1280 720
}

windowrule {
    name = small-sized-apps

    match:class = ^(blueman-manager|localsend)$

    float = true
    center = true
    size = 850 500
}

windowrule {
    name = media-viewers

    match:class = ^(mpv|qimgv|org\.kde\.okular)$

    float = true
    center = true
    size = 960 540
}

windowrule {
    name = dolphin

    match:class = ^(org\.kde\.dolphin)$

    float = true
    size = 1000 700
    move = (cursor_x-500) (cursor_y-350)
}

# Special:system
windowrule = border_size 0, match:float 0, match:workspace n[e:system]
windowrule = opacity 0.85, rounding 6, match:workspace n[e:system]

# Special:magic
windowrule = workspace special:magic silent, match:class ^(discord)$

# Special:music
windowrule = workspace special:music silent, match:class ^(Spotify)$

# Special:game
windowrule = opaque 1, rounding 6, match:workspace n[e:game]

##### Games #####

windowrule {
    name = steam-settings

    match:class = ^(steam)$
    match:title = ^(Steam Settings|Friends List$)

    float = true
    center = true
    min_size = 200 200
}

windowrule {
    name = main-games

    match:class = (steam_app_(default|[0-9]+))|gamescope|^(org.vinegarhq.Sober)$|(?i)^(Minecraft).*
    match:title = negative:^(Wallpaper UI)$|^()$

    immediate = true
    idle_inhibit = always
    workspace = special:game
    suppress_event = fullscreen
}

##### Launchers #####

windowrule {
    name = prism-launcher

    match:class = ^(org\.prismlauncher\.PrismLauncher)$
    match:title = ^(Console window).*

    float = true
    center = true
    size = 900 700
}

##### Utilities #####

windowrule {
    name = clipse

    match:class = ^(clipse)$

    float = true
    size = 350 400
    move = cursor_x cursor_y
    stay_focused = true
    border_size = 0
}

windowrule {
    name = wev

    match:class = ^(wev)$

    float = true
    center = true
    size = 300 300
}

##### Popups #####

windowrule {
    name = file-dialogues

    match:title = (Select|Open)( a)? (File|Folder|Document)(s)?.*|(?i).*(export|save).*(as|image|png|document).*|.* Properties|(?i)^(Create new|Location|Print).*

    float = true
    center = true
    persistent_size = false
}

windowrule {
    name = create-new-dialogue

    match:class = ^(org\.kde\.dolphin)$
    match:title = (?i)^(Create new).*

    stay_focused = true
}

##### Smart Gaps #####

# Single window workspaces
workspace = w[tv1], gapsout:5, gapsin:5
windowrule = border_size 0, rounding 6, match:float 0, match:workspace w[tv1]

# Fullscreen window
workspace = f[1], gapsout:5, gapsin:5, bordersize:0
windowrule = rounding 6, match:workspace f[1]

##### Quickshell #####
layerrule {
    name = quickshell

    match:namespace = ^(quickshell).*

    blur = true
    xray = false
    ignore_alpha = 0.1
    above_lock = 0
    animation = slide
}

##### Miscellaneous #####

windowrule {
    name = suppress-maximize

    match:class = .*

    suppress_event = #maximize
}

windowrule {
    name = fix-xwayland-drags

    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = true
}

windowrule {
    name = xwayland-video-bridge-fixes
    
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}