### GLOBAL VARIABLES ###

# Binds
    $main_mod = SUPER 

# Apps
    $terminal = alacritty
    $file_manager = dolphin
    $app_menu = rofi
    $browser = firefox

# Themes
    $wallpaper_id = 3416381037

    $layout = dwindle

    $rounding = 10
    $rounding_power = 2.5
    $active_border_color = rgb(04853d) rgb(091a0d) rgb(091a0d) rgb(04853d) 45deg
    $inactive_border_color = rgb(025524) rgb(050d07) rgb(050d07) rgb(025524) 45deg

    $win_active_opacity = 1.0
    $win_inactive_opacity = 1.0
    $win_fullscreen_opacity = 1.0

    $blur_enabled = true
    $blur_size = 4
    $blur_passes = 2

    $shadows_enabled = true
    $shadow_range = 10
    $shadow_active_color = rgba(000000aa)
    $shadow_inactive_color = rgba(00000088)